version: "3"
services:
  app:
    build: ./
    depends_on:
      - postgres
    ports:
      - ${port}:3000
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://psql@localhost:5432
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: psql
